version: "3.8"
networks:
  shared-network:
    driver: bridge

services:
  go:
    container_name: go
    networks:
      - shared-network
    build:
      context: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgresdb
      POSTGRES_PORT: 5432
    depends_on:
      - postgresdb
    links: 
      - postgresdb

  
  postgresdb:
    container_name: postgres
    networks:
      - shared-network
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes: 
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: 