# Use root/example as user/password credentials
version: '3.1'

volumes:
  mysqlvolume:

services:

  mysqldb:
    #platform: linux/x86_64  # fix for mac os m1, not accepted with kompose
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    volumes:
      - "mysqlvolume:/app/local-mysql-db-data"
 # adminer: # to access mysql in port 8080
 #   image: adminer
 #   restart: always
 #   ports:
 #     - 8080:8080
  go:
    build: .
    image: gcr.io/vectux-01/gomysqldocker
    #platform: linux/x86_64
    ports:
    - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
    - mysqldb
    links:
    - mysqldb


