apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: go
  name: go
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: go
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: go
    spec:
      containers:
        - env:
            - name: PORT
              value: "3000"
          image: gcr.io/vectux-01/gomysqldocker
          name: go
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
