apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mysqldb
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_DATABASE
              value: testdb
            - name: MYSQL_ROOT_PASSWORD
              value: example
          image: mysql
          name: mysqldb
          resources: {}
          volumeMounts:
            - mountPath: /app/local-mysql-db-data
              name: mysqlvolume
      restartPolicy: Always
      volumes:
        - name: mysqlvolume
          persistentVolumeClaim:
            claimName: mysqlvolume
status: {}
